services:
  nginx:
    container_name: ema-s7-micro-nginx-service
    build: ./nginx
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - user-service
      - game-service
      - combat-service
      - hero-service
      - items-service
      - leveldesign-service

  auth-service:
    container_name: ema-s7-micro-auth-service
    build: ./auth
    ports: 
      - "3001:3001"
    depends_on:
      - user-db
    
  user-service: 
    container_name: ema-s7-micro-user-service
    build: ./user
    ports:
      - "3002:3002"
    depends_on:
      - user-db
  
  game-service:
    container_name: ema-s7-micro-game-service
    build: ./game
    ports:
      - "3003:3003"
    depends_on:
      - hero-service
      - rabbitmq-service
      - combat-service

  combat-service:
    container_name: ema-s7-micro-combat-service
    build: ./combat
    ports:
      - "3004:3004"
    depends_on:
      - rabbitmq-service

  hero-service:
    container_name: ema-s7-micro-hero-service
    build: ./hero
    ports:
      - "3005:3005"
    environment:
      DATABASE_URL: "postgresql://user:password@hero-db:6500/herodb?schema=public"
      PORT: 3005
    depends_on:
      - hero-db

  items-service:
    container_name: ema-s7-micro-item-service
    build: ./item
    ports:
      - "3006:3006"
    environment:
      DATABASE_URL: "postgresql://itemuser:itempassword@item-db:5432/itemdb?schema=public"
    depends_on:
      - item-db

  leveldesign-service:
    container_name: ema-s7-micro-leveldesign-service
    build: ./level-design
    ports:
      - "3007:3007"

  save-service:
    container_name: ema-s7-micro-save-service
    build: ./save
    ports:
      - "3009:3009"
    depends_on:
      - save-db

  rabbitmq-service:
    container_name: ema-s7-micro-rabbitmq-service
    image: rabbitmq:3.10-management
    ports:
      - "5672:5672"
      - "15672:15672"

  user-db:
    container_name: ema-s7-micro-user-db
    image: mysql:oraclelinux9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_db
    ports:
      - "3306:3306"
    volumes:
      - user-db-data:/var/lib/mysql
  
  item-db:
    container_name: ema-s7-micro-item-db
    image: postgres:alpine3.23
    environment:
      - POSTGRES_USER=itemuser
      - POSTGRES_PASSWORD=itempassword
      - POSTGRES_DB=itemdb
    ports:
      - 5432:5432
    volumes:
      - item-db-data:/var/lib/postgresql/data/
      - ./init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  hero-db:
    container_name: ema-s7-micro-hero-db
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=herodb
    ports:
      - 6500:5432
    volumes:
      - hero-db-data:/var/lib/postgresql/data
      - ./init-scripts/migration.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d herodb"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  save-db:
    container_name: ema-s7-micro-save-db
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: itemuser
      MONGO_INITDB_ROOT_PASSWORD: itempassword
    ports:
      - "27017:27017"
    volumes:
      - save-db-data:/data/db
    restart: always

  front:
    container_name: ema-s7-micro-front-service
    build: ./front
    ports:
      - "8080:3000"
    depends_on:
      - nginx

volumes:
  user-db-data:
  item-db-data:
  hero-db-data:
  save-db-data: